# Generated by Django 5.0.2 on 2024-03-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_lecturer_delete_requisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='amount_in_words',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='cashier_signature',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='charge_to_account',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='forwarded_to_cashier_by',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='receiver_signature',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='supervisor_approval_date',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='supervisor_comment',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='voucher_number',
        ),
    ]
