# Generated by Django 5.0.2 on 2024-03-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_requisition_experience_requisition_name_and_more'),
        ('client', '0004_remove_lecturer_account_name_remove_lecturer_amount_and_more'),
    ]

    operations = [
    ]
