# Generated by Django 5.0.2 on 2024-04-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='publication',
        ),
    ]
