# Generated by Django 5.0.2 on 2024-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_lecturer_cashier_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='courseunits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='professional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
