# Generated by Django 5.0.2 on 2024-04-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_lecturer_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='courseunits',
            new_name='coursename',
        ),
    ]
