# Generated by Django 5.0.2 on 2024-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_lecturer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
